name: About Sam
favicon: null
layout_spectrum: 0.81877
typography_spectrum: 0.78392
title: Things about Sam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030218'
    - '#7b8e95'
    - '#9aada4'
    - '#60746d'
    - '#2e3935'
  brandStrength: 0.057710963068529963
  lightness: 0.5068646227009594
  saturation: 0.542947358218953
  rhythmicContrast: 0.5
purpose: []
