name: About Sam
favicon: null
layout_spectrum: 0.41639
typography_spectrum: 0.31723
title: Things about Sam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#d0d0d0'
    - '#858585'
    - '#646464'
    - '#3b3b3b'
  brandStrength: 0.057710963068529963
  lightness: 0.5068646227009594
  saturation: 0.542947358218953
  rhythmicContrast: 0.75
purpose: []
